### ISSUE TITLE
The link of pretrained weights

### ISSUE THREAD

**Issue by Chunmian-art** [H-EmbodVis/NAUTILUS#1]
Thank you for the great work on underwater embodied AI!

However, I noticed that the link to the pretrained weights appears to be broken.

Could you please take a look and update it when you have a chance?

Thanks again for your efforts!

**Comment by Chengnotwang** [comment]
> Thank you for the great work on underwater embodied AI!
> 
> However, I noticed that the link to the pretrained weights appears to be broken.
> 
> Could you please take a look and update it when you have a chance?
> 
> Thanks again for your efforts!

We apologize for the outdated link. Thanks for your attention, it has been corrected.

**Comment by Chunmian-art** [comment]
Thank you for the response!

I have checked the updated link, the link to qwen model is still broken.

Could you please check it again?

**Comment by Chengnotwang** [comment]
> Thank you for the response!
> 
> I have checked the updated link, the link to qwen model is still broken.
> 
> Could you please check it again?

Thanks for your endeavors. We verify the links as follows:

Nautilus (LLaVA): https://huggingface.co/H-EmbodVis/Nautilus-llava-instruct-7b
Nautilus (Qwen): https://huggingface.co/H-EmbodVis/Nautilus-qwen-instruct-7b
